import { app, BrowserWindow, ipcMain } from 'electron';
import './main/init/ipc-router'
import { initMidiRouter } from './main/init/midi_router';
import { initDmxLoop } from './main/init/dmx_loop';
import { initMenu } from './main/init/menu';
import { initAudioProtocol, registerAudioScheme } from './main/init/audio_protocol';
import { guardWindowClose, updateWindowTitle } from './main/show/document';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

registerAudioScheme();

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    // Same color as the app: shown in the area the page hasn't painted yet
    // when the window is resized quickly (white by default)
    backgroundColor: '#222',
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // The title shows the open show, don't let index.html's <title> replace it
  mainWindow.on('page-title-updated', (e) => e.preventDefault());
  updateWindowTitle(mainWindow);
  guardWindowClose(mainWindow);

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  //mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', async() => {
  try {
    initMenu()
    initAudioProtocol()
    await createWindow()
    await initMidiRouter()
    await initDmxLoop()

  }
  catch(e) {
    console.log(e)
    throw(e)
  }
  

});

// Quit when the window is closed, on macOS too: this is a single-window app,
// and the DMX loop and MIDI ports shouldn't keep running without it.
app.on('window-all-closed', () => {
  app.quit();
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
