import { app, BrowserWindow, ipcMain, shell } from 'electron';
import path from 'path';
import './main/init/ipc-router'
import { initMidiRouter } from './main/init/midi_router';
import { initDmxLoop } from './main/init/dmx_loop';
import { initMenu } from './main/init/menu';
import { initAboutPanel } from './main/init/about';
import { initAudioProtocol, registerAudioScheme } from './main/init/audio_protocol';
import { guardWindowClose, loadShowAtLaunch, openShowFromFinder, updateWindowTitle } from './main/show/document';
import { revealWindowEventually, showSplash } from './main/init/splash';
import { FixtureLibrary } from './main/fixture_library';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

registerAudioScheme();

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

// The app's window, once created (the splash is another window)
let mainWindow: BrowserWindow | null = null

// Shows opened from the Finder: double-clicked, or dropped on the Dock icon. One that launches the app
// comes before the window, even before 'ready': it's kept to start with
let showToOpenAtLaunch: string | null = null
app.on('open-file', (e, file) => {
  e.preventDefault()
  if (mainWindow && !mainWindow.isDestroyed()) {
    openShowFromFinder(mainWindow, file)
  } else {
    showToOpenAtLaunch = file
  }
})

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    width: 1024,
    height: 748,
    minWidth: 550,
    minHeight: 600,
    // Same color as the app: shown in the area the page hasn't painted yet
    // when the window is resized quickly (white by default)
    backgroundColor: '#222',
    // Shown once the app has rendered (see revealWindow), the splash showing meanwhile
    show: false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // Links to the web (e.g. the MainStage help in Interfaces) open in the browser, never in a window of the app
  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    if (url.startsWith('https://')) shell.openExternal(url)
    return { action: 'deny' }
  });

  // The title shows the open show, don't let index.html's <title> replace it
  mainWindow.on('page-title-updated', (e) => e.preventDefault());
  updateWindowTitle(mainWindow);
  guardWindowClose(mainWindow);

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  revealWindowEventually(mainWindow);

  // Open the DevTools.
  //mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', async() => {
  try {
    // Packaged builds get the icon from the bundle; `npm start` runs the stock Electron binary
    if (!app.isPackaged && process.platform === 'darwin') {
      app.dock?.setIcon(path.join(app.getAppPath(), 'assets/icon.png'))
    }
    // Fixture files people add: ~/Library/Application Support/Strobe/Fixtures on macOS
    FixtureLibrary.getInstance().watch(path.join(app.getPath('userData'), 'Fixtures'))
    initMenu()
    initAboutPanel()
    initAudioProtocol()
    showSplash()
    if (showToOpenAtLaunch) {
      loadShowAtLaunch(showToOpenAtLaunch)
      showToOpenAtLaunch = null
    }
    await createWindow()
    await initMidiRouter()
    await initDmxLoop()

  }
  catch(e) {
    console.log(e)
    throw(e)
  }
  

});

// Quit when the window is closed, on macOS too: this is a single-window app,
// and the DMX loop and MIDI ports shouldn't keep running without it.
app.on('window-all-closed', () => {
  app.quit();
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
